name: ci

on: push

jobs:
  test_install:
    runs-on: ubuntu-20.04

    steps:
      - uses: .github/workflows/install.yml

  check_format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install_tools
        run: pip install -r ./codetools/requirements.txt
      - name: black
        run: ./codetools/black/check.sh
      - name: isort
        run: ./codetools/isort/check.sh
      - name: pydocstyle
        run: ./codetools/pydocstyle/check.sh
      - name: darglint
        run: ./codetools/darglint/check.sh
      - name: pyflakes
        run: ./codetools/pyflakes/check.sh
      - name: sort-all
        run: |
          ./codetools/sort_all/fix.sh
          [[ -z $(git status -s) ]]
          git checkout -- .

  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: .github/workflows/install.yml
      - name: install requirements for pytest
        run: pip install pytest
      - name: run pytest
        run: pytest

  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: .github/workflows/install_dev.yml
      - name: install requirements for mypy
        run: pip install -r ./codetools/mypy/requirements.txt
      - name: run mypy
        run: ./codetools/mypy/check_opensource.sh

  docs:
    #runs-on: ubuntu-20.04
    steps:
      - uses: .github/workflows/install_dev.yml
actions/checkout@v2
      - name: install requirements for sphinx
        run: pip install -r ./docs/requirements.txt
      - name: sphinx
        run: make -C docs html
      - name: deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/build/html
          clean-exclude: .nojekyll