name: ci

on: push

jobs:
  test_install:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      # removing this because venv sourcing doesn't persist between steps:
      #- name: create virtualenv
      #  run: |
      #    pip install virtualenv
      #    virtualenv .venv
      #    . .venv/bin/activate
      - name: install serialization
        run: pip install ./serialization
      - name: install actor_controller
        run: pip install ./actor_controller
      - name: install rpi_controller
        run: pip install ./rpi_controller
      - name: install core
        run: pip install ./core
      - name: install standard_resources
        run: pip install ./standard_resources
      - name: install runner isaacgym
        #run: pip install ./runners/isaacgym[dev]
        run: echo "IsaacGym is not open source so sadly we cannot test this."
      - name: install runner mujoco
        run: pip install ./runners/mujoco
      - name: install genotype CPPNWIN
        run: |
          sudo apt install libcereal-dev
          pip install ./genotypes/cppnwin
      - name: view dirs2
        run: |
          sudo apt install -y tree && tree -L 2 ..

  check_format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install_tools
        run: pip install -r ./codetools/requirements.txt
      - name: black
        run: ./codetools/black/check.sh
      # disabling these for now cause they're too picky
      #- name: isort
      #  run: ./codetools/isort/check.sh
      #- name: pydocstyle
      #  run: ./codetools/pydocstyle/check.sh
      #- name: darglint
      #  run: ./codetools/darglint/check.sh
      #- name: pyflakes
      #  run: ./codetools/pyflakes/check.sh
      - name: sort-all
        run: |
          ./codetools/sort_all/fix.sh
          [[ -z $(git status -s) ]]
          git checkout -- .

  unit_tests:
    #uses: .github/workflows/install_dev.yml@${GITHUB_REF##*/}
    #uses: .github/workflows/install_dev.yml
    runs-on: ubuntu-20.04
    # https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: install repo (dev mode)
        run: bash .github/workflows/install_dev.sh
      - name: install pytest and erectus dependencies
        run: pip install -r experiments/robo_erectus/requirements.txt
      - name: create dummy display
        run: bash .github/workflows/install_dummy_screen.sh
      - name: run pytest
        run: pytest -v tests/

  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: install repo (dev)
        run: bash .github/workflows/install_dev.sh
      - name: install requirements for mypy
        run: pip install -r ./codetools/mypy/requirements.txt
      - name: run mypy
        run: ./codetools/mypy/check_opensource.sh

  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: install repo (dev)
        run: bash .github/workflows/install_dev.sh
      - name: install requirements for sphinx
        run: pip install -r ./docs/requirements.txt
      - name: sphinx
        run: make -C docs html
      - name: deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/build/html
          clean-exclude: .nojekyll